---
name: Build, Test, and Deploy to Github Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
workflow:
  jobs:
    building:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: npm ci
        - name: Build
          run: npm run build
    deploying:
      runs-on: ubuntu-latest
      needs: building
      steps:
        name: Deploy
        run: npm run deploy